### ISSUE TITLE
Not compatible with Solr 5.3.1

### ISSUE THREAD

**Issue by rik91** [LucidWorks/query-autofiltering-component#3]
I test your component under Solr 5.3.1, but I have an error when I call the requestHandler /autofilter :

{
  "error": {
    "msg": "java.lang.NoSuchMethodError: org.apache.solr.handler.component.ShardHandler.checkDistributed(Lorg/apache/solr/handler/component/ResponseBuilder;)V",
    "trace": "java.lang.RuntimeException: java.lang.NoSuchMethodError: org.apache.solr.handler.component.ShardHandler.checkDistributed(Lorg/apache/solr/handler/component/ResponseBuilder;)V\r\n\tat org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:618)\r\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:477)\r\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:214)\r\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:179)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\r\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\r\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\r\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)\r\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\r\n\tat org.eclipse.jetty.server.Server.handle(Server.java:499)\r\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\r\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\r\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\r\n\tat java.lang.Thread.run(Thread.java:745)\r\nCaused by: java.lang.NoSuchMethodError: org.apache.solr.handler.component.ShardHandler.checkDistributed(Lorg/apache/solr/handler/component/ResponseBuilder;)V\r\n\tat org.apache.solr.handler.component.QueryAutoFilteringComponent.addDistributedTerms(Unknown Source)\r\n\tat org.apache.solr.handler.component.QueryAutoFilteringComponent.buildFieldMap(Unknown Source)\r\n\tat org.apache.solr.handler.component.QueryAutoFilteringComponent.prepare(Unknown Source)\r\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:251)\r\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)\r\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2068)\r\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:669)\r\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:462)\r\n\t... 22 more\r\n",
    "code": 500
  }
}

It seem than since Solr 4.2, the function checkDistributed no longer exist as we can see in the changelog here : https://archive.apache.org/dist/lucene/solr/5.3.0/changes/Changes.html#v5.3.0.upgrading_from_solr_5.2

Could you update your code ?

Thanks

**Comment by SiddharthaAnand** [comment]
Not compatible with Solr5.5.0 too.
{
  "error": {
    "msg": "java.lang.NoSuchMethodError: org.apache.solr.handler.component.ShardHandler.checkDistributed(Lorg/apache/solr/handler/component/ResponseBuilder;)V",
    "trace": "java.lang.RuntimeException: java.lang.NoSuchMethodError: org.apache.solr.handler.component.ShardHandler.checkDistributed(Lorg/apache/solr/handler/component/ResponseBuilder;)V\n\tat org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:604)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:473)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:225)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:183)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:499)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: java.lang.NoSuchMethodError: org.apache.solr.handler.component.ShardHandler.checkDistributed(Lorg/apache/solr/handler/component/ResponseBuilder;)V\n\tat org.apache.solr.handler.component.QueryAutoFilteringComponent.addDistributedTerms(Unknown Source)\n\tat org.apache.solr.handler.component.QueryAutoFilteringComponent.buildFieldMap(Unknown Source)\n\tat org.apache.solr.handler.component.QueryAutoFilteringComponent.prepare(Unknown Source)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:246)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2082)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:670)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:458)\n\t... 22 more\n",
    "code": 500
  }
}

**Comment by detnavillus** [comment]
There was a method name change in the ShardHandler.java class from
checkDistributed to prepDistributed.  The source code needs to be changed
in the QueryAutofilteringComponent in order to compile with 5.3 and above.

Ted Sullivan
